[wazuh]
api_url =  # URL string
username = # USERNAME string
password = # PASSWORD string
port =     # PORT NUMBER int

[ollama]
api_url = # URL string
llm_model_name = # MODEL NAME string
port = # PORT NUMBER string
